version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # Nombre de la base de datos
      MYSQL_DATABASE: ${DB_NAME}
      # Nombre de usuario de la base de datos
      MYSQL_USER: ${DB_USERNAME}
      # Contraseña para el usuario de la base de datos
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Puerto expuesto por el container
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      # <Puerto Expuesto> : <PostgreSQL Puerto dentro del container>
      - '${DB_PORT}:3306'
      # El volumen my-db se crea en el sistema de archivos del host
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin:
volumes:
  db_data:
