export enum STATUS {
  ACTIVE = 'ACTIVO',
  INACTIVE = 'INACTIVO',
}

export enum AUDIT_STATUS {
  CREATE = 'CREADO',
  IN_CURSE = 'EN_CURSO',
  FINISHED = 'FINALIZADO',
  SUSPENDED = 'SUSPENDIDO',
}
