import { MigrationInterface, QueryRunner } from 'typeorm'
import { STATUS, TextService } from '@app/common'
import { User } from '../../src/users/entities'
import { Role } from '../../src/roles/entities'

export class Users1713742322774 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const DEFAULT_PASSWORD = '123'
    const pass = await TextService.encrypt(DEFAULT_PASSWORD)
    const users = [
      {
        names: 'ADMIN',
        lastNames: 'ADMIN',
        email: 'admin@gmail.com',
        password: pass,
        username: 'ADMIN',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '71981339',
        status: STATUS.ACTIVE,
        roles: ['1', '2', '3'],
        ci: '123456',
      },
      {
        names: 'GERENTE',
        lastNames: 'GERENTE',
        email: 'gerente@gmail.com',
        password: pass,
        username: 'GERENTE',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['2', '3', '4'],
        ci: '4231212',
      },
      {
        names: 'AUDIT-1',
        lastNames: 'AUDIT-1',
        email: 'audit1@gmail.com',
        password: pass,
        username: 'AUDIT-1',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '9886123',
      },
      {
        names: 'AUDIT-2',
        lastNames: 'AUDIT-2',
        email: 'audit2@gmail.com',
        password: pass,
        username: 'AUDIT-2',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '8612312',
      },
      {
        names: 'AUDIT-3',
        lastNames: 'AUDIT-3',
        email: 'audit3@gmail.com',
        password: pass,
        username: 'AUDIT-3',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['3'],
        ci: '9886123',
      },
      {
        names: 'AUDIT-4',
        lastNames: 'AUDIT-4',
        email: 'audit4@gmail.com',
        password: pass,
        username: 'AUDIT-4',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '7813623',
      },
      {
        names: 'AUDIT-5',
        lastNames: 'AUDIT-5',
        email: 'audit5@gmail.com',
        password: pass,
        username: 'AUDIT-5',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '1243623',
      },
      {
        names: 'AUDIT-6',
        lastNames: 'AUDIT-6',
        email: 'audit6@gmail.com',
        password: pass,
        username: 'AUDIT-6',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '5813613',
      },
      {
        names: 'AUDIT-7',
        lastNames: 'AUDIT-7',
        email: 'audit7@gmail.com',
        password: pass,
        username: 'AUDIT-7',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '7812411',
      },
      {
        names: 'AUDIT-8',
        lastNames: 'AUDIT-8',
        email: 'audi8@gmail.com',
        password: pass,
        username: 'AUDIT-8',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '62421234',
      },
      {
        names: 'AUDIT-9',
        lastNames: 'AUDIT-9',
        email: 'audit9@gmail.com',
        password: pass,
        username: 'AUDIT-9',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '7823433',
      },
      {
        names: 'AUDIT-10',
        lastNames: 'AUDIT-10',
        email: 'audit10@gmail.com',
        password: pass,
        username: 'AUDIT-10',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '9083623',
      },
      {
        names: 'AUDIT-11',
        lastNames: 'AUDIT-11',
        email: 'audit11@gmail.com',
        password: pass,
        username: 'AUDIT-11',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '9870891',
      },
      {
        names: 'AUDIT-12',
        lastNames: 'AUDIT-12',
        email: 'audit12@gmail.com',
        password: pass,
        username: 'AUDIT-12',
        createdAt: new Date(),
        updatedAt: new Date(),
        phone: '63201339',
        status: STATUS.ACTIVE,
        roles: ['4'],
        ci: '9886712',
      },
    ]
    const newUsers = users.map((user) => {
      return new User({
        names: user.names,
        lastNames: user.lastNames,
        email: user.email,
        password: user.password,
        username: user.username,
        createdAt: user.createdAt,
        updatedAt: user.updatedAt,
        phone: user.phone,
        status: user.status,
        ci: user.ci,
        roles: user.roles.map((role) => {
          return new Role({ id: role })
        }),
      })
    })
    await queryRunner.manager.save(newUsers)
  }
  //eslint-disable-next-line
  public async down(queryRunner: QueryRunner): Promise<void> {}
}
